name: edutech
description: Official Mobile App of Verzeo EduTech

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  intl: ^0.17.0
  cupertino_icons: ^1.0.2

  http: ^0.13.2
  # async package to add additional Cancellable operations
  async: ^2.5.0
  get_it: ^6.0.0
  provider: ^5.0.0
  # Stacked Arch
  stacked: ^2.0.0
  stacked_services: ^0.7.3
  stacked_themes: ^0.3.0
  shared_preferences: ^2.0.5
  stacked_firebase_auth: ^0.2.5

  #firebase
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.2
  firebase_storage: ^8.0.0
  image_picker: ^0.7.3

  #fonts
  google_fonts: ^2.0.0
  #svg
  flutter_svg:
  #url
  url_launcher: ^6.0.3
  #animation
  lottie: ^1.0.1
  animations: ^2.0.0
  #push
  #icons
  line_icons: ^2.0.1
  cached_network_image: ^3.0.0
  auto_size_text: ^2.1.0
  #id
  uuid: ^3.0.2
  #expandable view
  expandable: ^4.1.4

  shimmer: ^1.1.2
  #datepicker
  flutter_datetime_picker: ^1.5.1
  carousel_slider: ^3.0.0
  flutter_widget_from_html_core: ^0.6.0
  #image crop
  image_cropper: ^1.4.0

  flutter_slidable: ^0.6.0
  rxdart: ^0.26.0
  fl_chart: ^0.36.2
  collection: ^1.15.0
  #csv
  csv: ^5.0.0
  permission_handler: ^8.1.2
  ext_storage: ^1.0.3
  share_plus: ^2.1.4
dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/anim/
    - assets/icons/
